### ISSUE TITLE
Create a pre-commit hook

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/j2lint#28]
Many project host pre-commit hook definitions for users to import and leverage.

Here is my current example local pre-commit hook for j2lint:
```yaml
# See https://pre-commit.com/ for more information
repos:
  - repo: local
    hooks:
      - id: j2lint
        name: "lint: Jinja2"
        description: Lint Jinja2
        language: python
        entry: j2lint
```
